kind: Workflow
name: deploy
description: Deploy environment

steps:
  - script: ${var.authScript}
    name: setup
  - command: [deploy]
    name: deploy
    description: garden deploy
triggers:
  - events: [pull-request]
    environment: preview
